import test from 'node:test';
import assert from 'node:assert/strict';
import { renderHomePage } from '../public/website/home-page.js';

test('public home page renders the approved website experience', () => {
  const root = { innerHTML: '' };

  renderHomePage(root);

  assert.match(root.innerHTML, /Built for action\.<br><em>Priced to play\.<\/em>/);
  assert.match(root.innerHTML, /Quality custom teamwear that helps clubs and players get in the game\./);
  assert.match(root.innerHTML, /href="#studio"/);
  assert.match(root.innerHTML, />Game On\. /);
  assert.doesNotMatch(root.innerHTML, /Game On\. Start Designing/);
  assert.doesNotMatch(root.innerHTML, /Design Studio trial:/);
  assert.doesNotMatch(root.innerHTML, /Your kit\. Your identity\./);
  assert.match(root.innerHTML, /Quality teamwear made simple, affordable and reliable for community sport\./);
  assert.match(root.innerHTML, /data-help-category="faqs"/);
  assert.doesNotMatch(root.innerHTML, /data-help-category="studio"/);
  assert.doesNotMatch(root.innerHTML, /<h3>Pivot Design Studio Help<\/h3>/);
  assert.doesNotMatch(root.innerHTML, /data-help-category="club"/);
  assert.doesNotMatch(root.innerHTML, /<h3>Club Help Centre<\/h3>/);
  assert.doesNotMatch(root.innerHTML, /Who can access our club account\?/);
  assert.match(root.innerHTML, /What is currently available\?/);
  assert.match(root.innerHTML, /Pivot is currently working with one pilot club\. You can try the interactive Pivot Design Studio now/);
  assert.match(root.innerHTML, /What sports will Pivot support\?/);
  assert.match(root.innerHTML, /Pivot is starting with basketball, with more community sports planned as we grow\./);
  assert.match(root.innerHTML, /Clubs from any sport are welcome to <a href="#contact">register their interest<\/a>\./);
  assert.match(root.innerHTML, /Where does Pivot operate\?/);
  assert.match(root.innerHTML, /Pivot is local to Greater Bendigo and supplies and delivers teamwear across the region\./);
  assert.doesNotMatch(root.innerHTML, /teamwear only within Greater Bendigo/);
  assert.match(root.innerHTML, /How much will Pivot teamwear cost\?/);
  assert.match(root.innerHTML, /Pivot is committed to quality and fair pricing\. Confirmed prices will be published with each product when it becomes available\./);
  assert.doesNotMatch(root.innerHTML, /speculative batch rate|should be advertised/i);
  assert.match(root.innerHTML, /Is there any commitment\?/);
  assert.match(root.innerHTML, /You’re welcome to try the interactive Pivot Design Studio or register your interest without committing your club to a purchase\./);
  assert.doesNotMatch(root.innerHTML, /consent is governed|approved wording above/i);
  assert.doesNotMatch(root.innerHTML, /How can our club customise its teamwear\?/);
  assert.doesNotMatch(root.innerHTML, /Can our club have its own branded store\?/);
  assert.doesNotMatch(root.innerHTML, /What apparel will Pivot offer\?/);
  assert.doesNotMatch(root.innerHTML, /How do we register our club's interest\?/);
  assert.match(root.innerHTML, /Pivot is working with one pilot club to test a simpler teamwear experience/);
  assert.match(root.innerHTML, /our interactive Pivot Design Studio/);
  assert.match(root.innerHTML, /<span class="eyebrow">Contact us<\/span>/);
  assert.match(root.innerHTML, /id="open-club-interest"[^>]*aria-expanded="false"/);
  assert.match(root.innerHTML, /class="club-interest-form" id="club-interest-form"[^>]*hidden/);
  assert.match(root.innerHTML, /\*<\/span> Required fields/);
  assert.match(root.innerHTML, /Contact name <b class="required-mark"/);
  assert.match(root.innerHTML, /League or association <b class="required-mark"/);
  assert.match(root.innerHTML, /Club suburb or town <b class="required-mark"/);
  assert.match(root.innerHTML, /Register My Club’s Interest/);
  assert.match(root.innerHTML, /class="linked-interest-fields"/);
  assert.match(root.innerHTML, /mailto:hello@pivotteamwear\.com\?subject=Club%20Interest/);
  assert.match(root.innerHTML, /id="club-interest-sport"/);
  assert.match(root.innerHTML, /id="club-interest-association"/);
  assert.match(root.innerHTML, /id="club-interest-other-sport"/);
  assert.match(root.innerHTML, /id="club-interest-other-association"/);
  assert.match(root.innerHTML, /id="club-interest-locality"[^>]*required/);
  assert.match(root.innerHTML, /id="club-interest-other-locality-field"[^>]*hidden/);
  assert.match(root.innerHTML, /id="club-interest-other-locality"/);
  assert.doesNotMatch(root.innerHTML, /<optgroup/);
  assert.doesNotMatch(root.innerHTML, />Not sure</);
  assert.match(root.innerHTML, /Gridiron \(American football\)/);
  assert.match(root.innerHTML, /I agree to receive Pivot Teamwear news and updates by email\. I can unsubscribe at any time\./);
  assert.match(root.innerHTML, /Register Your Club’s Interest/);
  assert.doesNotMatch(root.innerHTML, /demonstrator/i);
});
